#!/bin/bash

mkdir -p ~/.local/var/
mkdir -p ~/.config/git/
mkdir -p ~/.config/procps/
mkdir -p ~/.vim/

declare -A DOT_FILES=(
    ["$HOME/.vim/vimrc"]=vimrc
    ["$HOME/.bashrc"]=bashrc
    ["$HOME/.tmux.conf"]=tmux.conf
    ["$HOME/.config/git/config"]=gitconfig
    ["$HOME/.config/procps/toprc"]=toprc
    ["$HOME/.gdbinit"]=gdbinit
    ["$HOME/.sqliterc"]=sqliterc
)
RC_REPO=$PWD
for path in "${!DOT_FILES[@]}"; do
    [ -e $path ] && echo Skipping $path && continue
    cd $(dirname $path)
    ln --relative -s $RC_REPO/${DOT_FILES[$path]} $(basename $path)
done
